### ISSUE TITLE
Develop the Application

### ISSUE THREAD

**Issue by mirasoldavila13** [mirasoldavila13/ProReadMeGenerator#1]
## User Story:

AS A developer
I WANT TO develop the application
SO THAT it generates a professional README.md file based on user input

## Acceptance Criteria:

1. `index.js` is created in the root directory.
2. Required modules (`inquirer`, `fs`, `path`) are imported.
3. An array of questions is defined to prompt the user for input.
4. A function to generate the README content is implemented.
5. A `Generated` directory is created if it doesn't exist.
6. The generated README is written to the `Generated` directory.

## Tasks:

- [x] Create `index.js` in the root directory.
- [x] Import required modules (`inquirer`, `fs`, `path`).
- [x] Define the questions to prompt the user.
- [x] Create a function to generate the README content.
- [x] Ensure a `Generated` directory is created if it doesn't exist.
- [x] Write the generated README to the `Generated` directory.
